name: Create build of website

on:
  push:
    branches:
        - master
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" 
      
      - name: Setup github bot
        run: |
            git config --global user.name "${GITHUB_ACTOR}"
            git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Build and stash site
        run: |
            git checkout master
            node build.js src
            mkdir untracked_build
            cp -r build/* untracked_build

      - name: Switch to gh-pages and commit
        run: |
            git checkout gh-pages || git checkout -b gh-pages
            git rm -rf .
            cp -r untracked_build/* .
            rm -rf untracked_build
            rm -rf build
            git add .
            git commit -m "Deploy from master branch" || echo "No changes to commit"
            git push origin gh-pages --force
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
